-- AlterTable
ALTER TABLE "orders" ADD COLUMN     "cep" VARCHAR(9) NOT NULL DEFAULT '',
ADD COLUMN     "city" VARCHAR(120) NOT NULL DEFAULT '',
ADD COLUMN     "state" VARCHAR(2) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "cep" VARCHAR(9) NOT NULL DEFAULT '',
ADD COLUMN     "city" VARCHAR(120) NOT NULL DEFAULT '',
ADD COLUMN     "state" VARCHAR(2) NOT NULL DEFAULT '';
